import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import About from './about';
import React from 'react';
import Button from '../components/elements/Button';
import btnStyles from '../components/elements/button/button.module.css';
import badgeStyles from '../components/elements/badge/badge.module.css';
import Badge from '../components/elements/badge';
import { HomepageShowcase } from '../components/elements/carousel/homepage-showcase';

export default function Home({ products }) {
  console.log(products);
  const [aboutText, setAboutText] = React.useState('Welcome to my about Page');
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

      <HomepageShowcase/>
      </main>
      <About text={aboutText} />
      <Button
        text="Click Me!"
        className={btnStyles.btn_primary}
        onClick={() => alert('Button Clicked')}
      />
      <Badge label="1" />
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch('https://fakestoreapi.com/products/');
  const products = await res.json();
  console.log(res.json());

  return {
    props: {
      products,
    },
  };
};
